<?php

namespace Database\Seeders;

use App\Models\Faculty;
use App\Models\User;
use Illuminate\Database\Seeder;

class FacultySeeder extends Seeder
{
    public function run(): void
    {
        // Order must match UserSeeder faculty list exactly
        $facultyData = [
            // JHS Math Teachers (Grades 7–10)
            [
                'email'           => 'jdelacruz@school.edu.ph',
                'employee_number' => 'EMP-001',
                'first_name'      => 'Juan',
                'middle_name'     => 'Santos',
                'last_name'       => 'dela Cruz',
                'birth_date'      => '1980-03-15',
                'gender'          => 'male',
                'address'         => '123 Rizal St., Manila',
                'contact_number'  => '09171234501',
                'department'      => 'Mathematics Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'assistant_professor',
                'specialization'  => 'Mathematics',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            [
                'email'           => 'msantos@school.edu.ph',
                'employee_number' => 'EMP-002',
                'first_name'      => 'Maria',
                'middle_name'     => 'Cruz',
                'last_name'       => 'Santos',
                'birth_date'      => '1983-07-22',
                'gender'          => 'female',
                'address'         => '45 Bonifacio Ave., Quezon City',
                'contact_number'  => '09171234502',
                'department'      => 'Mathematics Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'instructor',
                'specialization'  => 'Mathematics',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            [
                'email'           => 'rcastillo@school.edu.ph',
                'employee_number' => 'EMP-003',
                'first_name'      => 'Ricardo',
                'middle_name'     => null,
                'last_name'       => 'Castillo',
                'birth_date'      => '1978-11-05',
                'gender'          => 'male',
                'address'         => '78 Mabini St., Pasay',
                'contact_number'  => '09171234503',
                'department'      => 'Mathematics Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'associate_professor',
                'specialization'  => 'Mathematics',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            // SHS Math Teacher
            [
                'email'           => 'jreyes@school.edu.ph',
                'employee_number' => 'EMP-004',
                'first_name'      => 'Jose',
                'middle_name'     => 'Lim',
                'last_name'       => 'Reyes',
                'birth_date'      => '1985-04-18',
                'gender'          => 'male',
                'address'         => '12 Luna St., Makati',
                'contact_number'  => '09171234504',
                'department'      => 'Mathematics Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'assistant_professor',
                'specialization'  => 'Statistics and Applied Mathematics',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            // JHS Science Teachers
            [
                'email'           => 'agarcia@school.edu.ph',
                'employee_number' => 'EMP-005',
                'first_name'      => 'Ana',
                'middle_name'     => 'Bautista',
                'last_name'       => 'Garcia',
                'birth_date'      => '1982-09-30',
                'gender'          => 'female',
                'address'         => '34 Gomez St., Caloocan',
                'contact_number'  => '09171234505',
                'department'      => 'Science Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'instructor',
                'specialization'  => 'Biology and Earth Science',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            [
                'email'           => 'pflores@school.edu.ph',
                'employee_number' => 'EMP-006',
                'first_name'      => 'Pedro',
                'middle_name'     => 'Aquino',
                'last_name'       => 'Flores',
                'birth_date'      => '1979-01-12',
                'gender'          => 'male',
                'address'         => '89 Del Pilar St., Manila',
                'contact_number'  => '09171234506',
                'department'      => 'Science Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'assistant_professor',
                'specialization'  => 'Chemistry and Physics',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            // SHS Science Teachers
            [
                'email'           => 'rmendoza@school.edu.ph',
                'employee_number' => 'EMP-007',
                'first_name'      => 'Rosa',
                'middle_name'     => 'Villanueva',
                'last_name'       => 'Mendoza',
                'birth_date'      => '1981-06-25',
                'gender'          => 'female',
                'address'         => '56 Tandang Sora, Quezon City',
                'contact_number'  => '09171234507',
                'department'      => 'Science Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'associate_professor',
                'specialization'  => 'Physical Science',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            [
                'email'           => 'fcruz@school.edu.ph',
                'employee_number' => 'EMP-008',
                'first_name'      => 'Fernando',
                'middle_name'     => null,
                'last_name'       => 'Cruz',
                'birth_date'      => '1977-12-08',
                'gender'          => 'male',
                'address'         => '23 Blumentritt St., Manila',
                'contact_number'  => '09171234508',
                'department'      => 'Science Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'instructor',
                'specialization'  => 'Earth and Life Science',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            // JHS English Teachers
            [
                'email'           => 'ctorres@school.edu.ph',
                'employee_number' => 'EMP-009',
                'first_name'      => 'Carlos',
                'middle_name'     => 'Ramos',
                'last_name'       => 'Torres',
                'birth_date'      => '1984-02-14',
                'gender'          => 'male',
                'address'         => '67 España Blvd., Manila',
                'contact_number'  => '09171234509',
                'department'      => 'English Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'instructor',
                'specialization'  => 'English Language and Literature',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            [
                'email'           => 'lramos@school.edu.ph',
                'employee_number' => 'EMP-010',
                'first_name'      => 'Luz',
                'middle_name'     => 'Santos',
                'last_name'       => 'Ramos',
                'birth_date'      => '1986-08-03',
                'gender'          => 'female',
                'address'         => '90 Taft Ave., Manila',
                'contact_number'  => '09171234510',
                'department'      => 'English Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'instructor',
                'specialization'  => 'English Communication',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            [
                'email'           => 'gaquino@school.edu.ph',
                'employee_number' => 'EMP-011',
                'first_name'      => 'Gloria',
                'middle_name'     => 'dela Cruz',
                'last_name'       => 'Aquino',
                'birth_date'      => '1975-05-20',
                'gender'          => 'female',
                'address'         => '11 Padre Faura, Ermita, Manila',
                'contact_number'  => '09171234511',
                'department'      => 'English Department',
                'position'        => 'Senior Teacher',
                'rank'            => 'associate_professor',
                'specialization'  => 'English Language Arts',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            // SHS English/Humanities Teachers
            [
                'email'           => 'cbautista@school.edu.ph',
                'employee_number' => 'EMP-012',
                'first_name'      => 'Carmen',
                'middle_name'     => 'Lopez',
                'last_name'       => 'Bautista',
                'birth_date'      => '1983-10-17',
                'gender'          => 'female',
                'address'         => '44 Shaw Blvd., Mandaluyong',
                'contact_number'  => '09171234512',
                'department'      => 'English Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'assistant_professor',
                'specialization'  => 'Communication and Literature',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            [
                'email'           => 'nlim@school.edu.ph',
                'employee_number' => 'EMP-013',
                'first_name'      => 'Natividad',
                'middle_name'     => null,
                'last_name'       => 'Lim',
                'birth_date'      => '1980-07-09',
                'gender'          => 'female',
                'address'         => '33 Ortigas Ave., Pasig',
                'contact_number'  => '09171234513',
                'department'      => 'English Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'instructor',
                'specialization'  => '21st Century Literature and Media',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            // Filipino/EsP Teachers
            [
                'email'           => 'mlopez@school.edu.ph',
                'employee_number' => 'EMP-014',
                'first_name'      => 'Miguel',
                'middle_name'     => 'Garcia',
                'last_name'       => 'Lopez',
                'birth_date'      => '1978-04-01',
                'gender'          => 'male',
                'address'         => '100 Katipunan Ave., Quezon City',
                'contact_number'  => '09171234514',
                'department'      => 'Filipino Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'assistant_professor',
                'specialization'  => 'Filipino Wika at Panitikan',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            [
                'email'           => 'egonzales@school.edu.ph',
                'employee_number' => 'EMP-015',
                'first_name'      => 'Elena',
                'middle_name'     => 'Reyes',
                'last_name'       => 'Gonzales',
                'birth_date'      => '1982-11-28',
                'gender'          => 'female',
                'address'         => '77 C.M. Recto Ave., Manila',
                'contact_number'  => '09171234515',
                'department'      => 'Filipino Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'instructor',
                'specialization'  => 'Filipino at Edukasyon sa Pagpapakatao',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            // MAPEH / AP Teachers
            [
                'email'           => 'rvillanueva@school.edu.ph',
                'employee_number' => 'EMP-016',
                'first_name'      => 'Roberto',
                'middle_name'     => 'Santos',
                'last_name'       => 'Villanueva',
                'birth_date'      => '1976-09-14',
                'gender'          => 'male',
                'address'         => '22 Adriatico St., Malate, Manila',
                'contact_number'  => '09171234516',
                'department'      => 'MAPEH Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'instructor',
                'specialization'  => 'Music, Arts, Physical Education, Health',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            [
                'email'           => 'jdelarosa@school.edu.ph',
                'employee_number' => 'EMP-017',
                'first_name'      => 'Josephine',
                'middle_name'     => 'Cruz',
                'last_name'       => 'Dela Rosa',
                'birth_date'      => '1985-03-22',
                'gender'          => 'female',
                'address'         => '55 Arnaiz Ave., Makati',
                'contact_number'  => '09171234517',
                'department'      => 'Social Studies Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'instructor',
                'specialization'  => 'Araling Panlipunan',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            // TLE Teacher
            [
                'email'           => 'esantos@school.edu.ph',
                'employee_number' => 'EMP-018',
                'first_name'      => 'Emmanuel',
                'middle_name'     => 'Flores',
                'last_name'       => 'Santos',
                'birth_date'      => '1981-06-11',
                'gender'          => 'male',
                'address'         => '88 Aurora Blvd., Cubao, Quezon City',
                'contact_number'  => '09171234518',
                'department'      => 'Technology and Livelihood Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'instructor',
                'specialization'  => 'Industrial Technology and Home Economics',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            // SHS Humanities: Personal Development & Media Lit
            [
                'email'           => 'mnavarro@school.edu.ph',
                'employee_number' => 'EMP-019',
                'first_name'      => 'Maricel',
                'middle_name'     => null,
                'last_name'       => 'Navarro',
                'birth_date'      => '1984-01-30',
                'gender'          => 'female',
                'address'         => '19 Gilmore Ave., San Juan',
                'contact_number'  => '09171234519',
                'department'      => 'Social Sciences Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'instructor',
                'specialization'  => 'Personal Development and Psychology',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
            [
                'email'           => 'areyes@school.edu.ph',
                'employee_number' => 'EMP-020',
                'first_name'      => 'Antonio',
                'middle_name'     => 'Bautista',
                'last_name'       => 'Reyes',
                'birth_date'      => '1979-08-19',
                'gender'          => 'male',
                'address'         => '66 EDSA, Mandaluyong',
                'contact_number'  => '09171234520',
                'department'      => 'Social Sciences Department',
                'position'        => 'Subject Teacher',
                'rank'            => 'assistant_professor',
                'specialization'  => 'Media and Information Literacy',
                'employment_type' => 'full_time',
                'status'          => 'active',
            ],
        ];

        foreach ($facultyData as $data) {
            $user = User::where('email', $data['email'])->first();

            Faculty::create([
                'user_id'         => $user?->id,
                'employee_number' => $data['employee_number'],
                'first_name'      => $data['first_name'],
                'middle_name'     => $data['middle_name'],
                'last_name'       => $data['last_name'],
                'birth_date'      => $data['birth_date'],
                'gender'          => $data['gender'],
                'address'         => $data['address'],
                'contact_number'  => $data['contact_number'],
                'department'      => $data['department'],
                'position'        => $data['position'],
                'rank'            => $data['rank'],
                'specialization'  => $data['specialization'],
                'employment_type' => $data['employment_type'],
                'status'          => $data['status'],
            ]);
        }
    }
}
